=== Ovan741852/Unone/docs/mesh.schema.json
{
  "$comment": "Generated from Rust deserialization types by game schema. Do not edit. Runtime semantic validators additionally check ranges, references, formats and capabilities.",
  "$defs": {
    "MeshLod": {
      "additionalProperties": false,
      "properties": {
        "distance": {
          "format": "float",
          "type": "number"
        },
        "indices": {
          "items": {
            "format": "uint32",
            "minimum": 0,
            "type": "integer"
          },
          "type": "array"
        },
        "positions": {
          "items": {
            "format": "float",
            "type": "number"
          },
          "type": "array"
        },
        "uvs": {
          "items": {
            "format": "float",
            "type": "number"
          },
          "type": "array"
        }
      },
      "required": [
        "distance",
        "positions",
        "uvs",
        "indices"
      ],
      "type": "object"
    }
  },
  "$id": "https://unone.dev/schema/mesh.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "indices": {
      "items": {
        "format": "uint32",
        "minimum": 0,
        "type": "integer"
      },
      "type": "array"
    },
    "lods": {
      "items": {
        "$ref": "#/$defs/MeshLod"
      },
      "type": "array"
    },
    "positions": {
      "items": {
        "format": "float",
        "type": "number"
      },
      "type": "array"
    },
    "texture": {
      "type": "string"
    },
    "uvs": {
      "items": {
        "format": "float",
        "type": "number"
      },
      "type": "array"
    },
    "version": {
      "format": "uint32",
      "minimum": 0,
      "type": "integer"
    }
  },
  "required": [
    "version",
    "positions",
    "uvs",
    "indices",
    "texture"
  ],
  "title": "MeshAsset",
  "type": "object"
}

=== Ovan741852/Unone/_Games/wuxia-sandbox/assets/imported/planks.mesh.json
{"version":1,"positions":[-0.5,0,-0.2028162,-0.5,0.03,-0.3514081,-0.5,0,-0.3514081,-0.5,0.03,-0.2028162,0.5,0.03,-0.2028162,0.5,0,-0.3514081,0.5,0.03,-0.3514081,0.5,0,-0.2028162,-0.5,0.03,-0.3514081,0.5,0,-0.3514081,-0.5,0,-0.3514081,0.5,0.03,-0.3514081,0.5,0.03,-0.2028162,-0.5,0,-0.2028162,0.5,0,-0.2028162,-0.5,0.03,-0.2028162,-0.5,0,-0.2028162,0.5,0,-0.3514081,0.5,0,-0.2028162,-0.5,0,-0.3514081,0.5,0.03,-0.3514081,-0.5,0.03,-0.2028162,0.5,0.03,-0.2028162,-0.5,0.03,-0.3514081,0.5,0.03,0.3514081,0.5,0,0.2028162,0.5,0.03,0.2028162,0.5,0,0.3514081,-0.5,0,0.3514081,-0.5,0.03,0.2028162,-0.5,0,0.2028162,-0.5,0.03,0.3514081,-0.5,0,0.3514081,0.5,0,0.2028162,0.5,0,0.3514081,-0.5,0,0.2028162,-0.5,0.03,0.2028162,0.5,0,0.2028162,-0.5,0,0.2028162,0.5,0.03,0.2028162,0.5,0.03,0.3514081,-0.5,0,0.3514081,0.5,0,0.3514081,-0.5,0.03,0.3514081,0.5,0.03,0.2028162,-0.5,0.03,0.3514081,0.5,0.03,0.3514081,-0.5,0.03,0.2028162,-0.1811265,0.06,0.5,-0.3297184,0.03,0.5,-0.1811265,0.03,0.5,-0.3297184,0.06,0.5,-0.1811265,0.06,-0.5,-0.3297184,0.06,0.5,-0.1811265,0.06,0.5,-0.3297184,0.06,-0.5,-0.3297184,0.06,-0.5,-0.1811265,0.03,-0.5,-0.3297184,0.03,-0.5,-0.1811265,0.06,-0.5,-0.3297184,0.03,0.5,-0.1811265,0.03,-0.5,-0.1811265,0.03,0.5,-0.3297184,0.03,-0.5,0.5,0.06,-0.5,0.3514081,0.06,0.5,0.5,0.06,0.5,0.3514081,0.06,-0.5,-0.1594367,0.03,0.5,-0.01084486,0.03,-0.5,-0.01084486,0.03,0.5,-0.1594367,0.03,-0.5,0.01084486,0.03,0.5,0.1594367,0.03,-0.5,0.1594367,0.03,0.5,0.01084486,0.03,-0.5,0.1594367,0.06,-0.5,0.01084486,0.06,0.5,0.1594367,0.06,0.5,0.01084486,0.06,-0.5,-0.1594367,0.06,-0.5,-0.01084486,0.03,-0.5,-0.1594367,0.03,-0.5,-0.01084486,0.06,-0.5,0.5,0.06,0.5,0.3514081,0.03,0.5,0.5,0.03,0.5,0.3514081,0.06,0.5,-0.01084486,0.06,0.5,-0.1594367,0.03,0.5,-0.01084486,0.03,0.5,-0.1594367,0.06,0.5,-0.3514081,0.06,-0.5,-0.5,0.06,0.5,-0.3514081,0.06,0.5,-0.5,0.06,-0.5,0.3297184,0.06,-0.5,0.1811265,0.06,0.5,0.3297184,0.06,0.5,0.1811265,0.06,-0.5,0.3514081,0.06,-0.5,0.5,0.03,-0.5,0.3514081,0.03,-0.5,0.5,0.06,-0.5,0.3297184,0.06,0.5,0.1811265,0.03,0.5,0.3297184,0.03,0.5,0.1811265,0.06,0.5,0.1811265,0.03,0.5,0.3297184,0.03,-0.5,0.3297184,0.03,0.5,0.1811265,0.03,-0.5,-0.01084486,0.06,-0.5,-0.1594367,0.06,0.5,-0.01084486,0.06,0.5,-0.1594367,0.06,-0.5,-0.5,0.03,0.5,-0.3514081,0.03,-0.5,-0.3514081,0.03,0.5,-0.5,0.03,-0.5,0.01084486,0.06,-0.5,0.1594367,0.03,-0.5,0.01084486,0.03,-0.5,0.1594367,0.06,-0.5,-0.5,0.06,-0.5,-0.3514081,0.03,-0.5,-0.5,0.03,-0.5,-0.3514081,0.06,-0.5,0.5,0.03,0.5,0.3514081,0.03,-0.5,0.5,0.03,-0.5,0.3514081,0.03,0.5,0.1594367,0.06,0.5,0.01084486,0.03,0.5,0.1594367,0.03,0.5,0.01084486,0.06,0.5,0.1811265,0.06,-0.5,0.3297184,0.03,-0.5,0.1811265,0.03,-0.5,0.3297184,0.06,-0.5,-0.3514081,0.06,0.5,-0.5,0.03,0.5,-0.3514081,0.03,0.5,-0.5,0.06,0.5,-0.3297184,0.03,-0.5,-0.3297184,0.06,0.5,-0.3297184,0.06,-0.5,-0.3297184,0.03,0.5,-0.1811265,0.06,0.5,-0.1811265,0.03,-0.5,-0.1811265,0.06,-0.5,-0.1811265,0.03,0.5,0.3514081,0.03,0.5,0.3514081,0.06,-0.5,0.3514081,0.03,-0.5,0.3514081,0.06,0.5,0.5,0.06,-0.5,0.5,0.03,0.5,0.5,0.03,-0.5,0.5,0.06,0.5,-0.3514081,0.06,0.5,-0.3514081,0.03,-0.5,-0.3514081,0.06,-0.5,-0.3514081,0.03,0.5,-0.1594367,0.03,-0.5,-0.1594367,0.06,0.5,-0.1594367,0.06,-0.5,-0.1594367,0.03,0.5,0.1811265,0.03,0.5,0.1811265,0.06,-0.5,0.1811265,0.03,-0.5,0.1811265,0.06,0.5,-0.01084486,0.06,0.5,-0.01084486,0.03,-0.5,-0.01084486,0.06,-0.5,-0.01084486,0.03,0.5,0.3297184,0.06,-0.5,0.3297184,0.03,0.5,0.3297184,0.03,-0.5,0.3297184,0.06,0.5,-0.5,0.03,-0.5,-0.5,0.06,0.5,-0.5,0.06,-0.5,-0.5,0.03,0.5,0.1594367,0.06,-0.5,0.1594367,0.03,0.5,0.1594367,0.03,-0.5,0.1594367,0.06,0.5,0.01084486,0.03,-0.5,0.01084486,0.06,0.5,0.01084486,0.06,-0.5,0.01084486,0.03,0.5],"uvs":[0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.075,0.59375,0.075,0.59375,0.075,0.59375,0.075,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.075,0.59375,0.175,0.59375,0.075,0.59375,0.175,0.59375,0.175,0.59375,0.075],"indices":[0,1,2,1,0,3,4,5,6,5,4,7,8,9,10,9,8,11,12,13,14,13,12,15,16,17,18,17,16,19,20,21,22,21,20,23,24,25,26,25,24,27,28,29,30,29,28,31,32,33,34,33,32,35,36,37,38,37,36,39,40,41,42,41,40,43,44,45,46,45,44,47,48,49,50,49,48,51,52,53,54,53,52,55,56,57,58,57,56,59,60,61,62,61,60,63,64,65,66,65,64,67,68,69,70,69,68,71,72,73,74,73,72,75,76,77,78,77,76,79,80,81,82,81,80,83,84,85,86,85,84,87,88,89,90,89,88,91,92,93,94,93,92,95,96,97,98,97,96,99,100,101,102,101,100,103,104,105,106,105,104,107,108,109,110,109,108,111,112,113,114,113,112,115,116,117,118,117,116,119,120,121,122,121,120,123,124,125,126,125,124,127,128,129,130,129,128,131,132,133,134,133,132,135,136,137,138,137,136,139,140,141,142,141,140,143,144,145,146,145,144,147,148,149,150,149,148,151,152,153,154,153,152,155,156,157,158,157,156,159,160,161,162,161,160,163,164,165,166,165,164,167,168,169,170,169,168,171,172,173,174,173,172,175,176,177,178,177,176,179,180,181,182,181,180,183,184,185,186,185,184,187,188,189,190,189,188,191,0,1,2,1,0,3,4,5,6,5,4,7,8,9,10,9,8,11,12,13,14,13,12,15,16,17,18,17,16,19,20,21,22,21,20,23,24,25,26,25,24,27,28,29,30,29,28,31,32,33,34,33,32,35,36,37,38,37,36,39,40,41,42,41,40,43,44,45,46,45,44,47,48,49,50,49,48,51,52,53,54,53,52,55,56,57,58,57,56,59,60,61,62,61,60,63,64,65,66,65,64,67,68,69,70,69,68,71,72,73,74,73,72,75,76,77,78,77,76,79,80,81,82,81,80,83,84,85,86,85,84,87,88,89,90,89,88,91,92,93,94,93,92,95,96,97,98,97,96,99,100,101,102,101,100,103,104,105,106,105,104,107,108,109,110,109,108,111,112,113,114,113,112,115,116,117,118,117,116,119,120,121,122,121,120,123,124,125,126,125,124,127,128,129,130,129,128,131,132,133,134,133,132,135,136,137,138,137,136,139,140,141,142,141,140,143,144,145,146,145,144,147,148,149,150,149,148,151,152,153,154,153,152,155,156,157,158,157,156,159,160,161,162,161,160,163,164,165,166,165,164,167,168,169,170,169,168,171,172,173,174,173,172,175,176,177,178,177,176,179,180,181,182,181,180,183,184,185,186,185,184,187,188,189,190,189,188,191],"texture":"texture://town"}
